//File :- data/schoolGallery.ts
// AUTO-GENERATED by scripts/genSchoolGallery.mjs — do not edit photo lists by hand.
// Catalogs the local images under public/schoolimages and public/groupedImages.
// (HEIC files are intentionally excluded — browsers cannot render them.)

export type LocalPhoto = { src: string; alt: string };

export type LocalGallery = {
  name: string;
  slug: string;
  cover: string;
  count: number;
  createdOn: string;
  photos: LocalPhoto[];
};

const raw: Omit<LocalGallery, "cover">[] = [
  {
    "name": "Basketball",
    "slug": "basketball",
    "count": 4,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/basket ball/_DSC9757.JPG",
        "alt": "Basketball at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/basket ball/_DSC9782.JPG",
        "alt": "Basketball at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/basket ball/_DSC9783.JPG",
        "alt": "Basketball at Montessori Prime — photo 3"
      },
      {
        "src": "/groupedImages/basket ball/_DSC9832.JPG",
        "alt": "Basketball at Montessori Prime — photo 4"
      }
    ]
  },
  {
    "name": "Chairman Sir",
    "slug": "chairman-sir",
    "count": 8,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/chair man sir/_DSC8356.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8357.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8360.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 3"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8514.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 4"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8520.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 5"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8523.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 6"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8567.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 7"
      },
      {
        "src": "/groupedImages/chair man sir/_DSC8570.JPG",
        "alt": "Chairman Sir at Montessori Prime — photo 8"
      }
    ]
  },
  {
    "name": "Computer Lab",
    "slug": "computer-lab",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/compuer lab/_DSC9397.JPG",
        "alt": "Computer Lab at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/compuer lab/_DSC9398.JPG",
        "alt": "Computer Lab at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/compuer lab/_DSC9440.JPG",
        "alt": "Computer Lab at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Hostel",
    "slug": "hostel",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/hostel/_DSC9226.JPG",
        "alt": "Hostel at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/hostel/_DSC9229.JPG",
        "alt": "Hostel at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/hostel/_DSC9241.JPG",
        "alt": "Hostel at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Laboratory",
    "slug": "laboratory",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/lab/_DSC9444.JPG",
        "alt": "Laboratory at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/lab/_DSC9452.JPG",
        "alt": "Laboratory at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "Library",
    "slug": "library",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/library/_DSC9468.JPG",
        "alt": "Library at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/library/_DSC9471.JPG",
        "alt": "Library at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/library/_DSC9476.JPG",
        "alt": "Library at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Martial Arts",
    "slug": "martial-arts",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/mar.art/_DSC9888.JPG",
        "alt": "Martial Arts at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/mar.art/_DSC9898.JPG",
        "alt": "Martial Arts at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "Dining Hall",
    "slug": "dining-hall",
    "count": 13,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/mess/_DSC0098.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/mess/_DSC0131.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/mess/_DSC8356.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 3"
      },
      {
        "src": "/groupedImages/mess/_DSC8357.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 4"
      },
      {
        "src": "/groupedImages/mess/_DSC8360.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 5"
      },
      {
        "src": "/groupedImages/mess/_DSC8514.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 6"
      },
      {
        "src": "/groupedImages/mess/_DSC8520.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 7"
      },
      {
        "src": "/groupedImages/mess/_DSC8523.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 8"
      },
      {
        "src": "/groupedImages/mess/_DSC8567.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 9"
      },
      {
        "src": "/groupedImages/mess/_DSC8570.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 10"
      },
      {
        "src": "/groupedImages/mess/_DSC9178.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 11"
      },
      {
        "src": "/groupedImages/mess/_DSC9192.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 12"
      },
      {
        "src": "/groupedImages/mess/_DSC9194.JPG",
        "alt": "Dining Hall at Montessori Prime — photo 13"
      }
    ]
  },
  {
    "name": "Others",
    "slug": "others",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/others/_DSC0196.JPG",
        "alt": "Others at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/others/_DSC0222.JPG",
        "alt": "Others at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "PA",
    "slug": "pa",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/PA/_DSC9534.JPG",
        "alt": "PA at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/PA/_DSC9537.JPG",
        "alt": "PA at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/PA/_DSC9548.JPG",
        "alt": "PA at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "President",
    "slug": "president",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/president/_DSC0098.JPG",
        "alt": "President at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/president/_DSC0131.JPG",
        "alt": "President at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "School",
    "slug": "school",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/school/_DSC9134.JPG",
        "alt": "School at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/school/_DSC9151.JPG",
        "alt": "School at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "Study Hours",
    "slug": "study-hours",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/study hr/_DSC9241.JPG",
        "alt": "Study Hours at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/study hr/_DSC9244.JPG",
        "alt": "Study Hours at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "Teaching",
    "slug": "teaching",
    "count": 4,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/teaching/_DSC9264.JPG",
        "alt": "Teaching at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/teaching/_DSC9267.JPG",
        "alt": "Teaching at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/teaching/_DSC9332.JPG",
        "alt": "Teaching at Montessori Prime — photo 3"
      },
      {
        "src": "/groupedImages/teaching/_DSC9335.JPG",
        "alt": "Teaching at Montessori Prime — photo 4"
      }
    ]
  },
  {
    "name": "Technology",
    "slug": "technology",
    "count": 1,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/tecnolagy/_DSC0210.JPG",
        "alt": "Technology at Montessori Prime — photo 1"
      }
    ]
  },
  {
    "name": "Test",
    "slug": "test",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/test/_DSC9628.JPG",
        "alt": "Test at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/test/_DSC9629.JPG",
        "alt": "Test at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/test/_DSC9632.JPG",
        "alt": "Test at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Testimonials",
    "slug": "testimonials",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/testimony/_DSC9728.JPG",
        "alt": "Testimonials at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/testimony/_DSC9729.JPG",
        "alt": "Testimonials at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/testimony/_DSC9732.JPG",
        "alt": "Testimonials at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "TP",
    "slug": "tp",
    "count": 2,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/TP/_DSC9594.JPG",
        "alt": "TP at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/TP/_DSC9608.JPG",
        "alt": "TP at Montessori Prime — photo 2"
      }
    ]
  },
  {
    "name": "Trf",
    "slug": "trf",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/trf/_DSC9942.JPG",
        "alt": "Trf at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/trf/_DSC9990.JPG",
        "alt": "Trf at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/trf/_DSC9998.JPG",
        "alt": "Trf at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Volleyball",
    "slug": "volleyball",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/vollyball/_DSC0023.JPG",
        "alt": "Volleyball at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/vollyball/_DSC0024.JPG",
        "alt": "Volleyball at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/vollyball/_DSC0026.JPG",
        "alt": "Volleyball at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Yoga",
    "slug": "yoga",
    "count": 3,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/groupedImages/yoga/_DSC9046.JPG",
        "alt": "Yoga at Montessori Prime — photo 1"
      },
      {
        "src": "/groupedImages/yoga/_DSC9067.JPG",
        "alt": "Yoga at Montessori Prime — photo 2"
      },
      {
        "src": "/groupedImages/yoga/_DSC9100.JPG",
        "alt": "Yoga at Montessori Prime — photo 3"
      }
    ]
  },
  {
    "name": "Campus Life",
    "slug": "campus-life",
    "count": 145,
    "createdOn": "27/05/2026 12:00:00 PM",
    "photos": [
      {
        "src": "/schoolimages/1 (1).jpeg",
        "alt": "Montessori Prime campus — photo 1"
      },
      {
        "src": "/schoolimages/01 (1).jpg",
        "alt": "Montessori Prime campus — photo 2"
      },
      {
        "src": "/schoolimages/1 (1).jpg",
        "alt": "Montessori Prime campus — photo 3"
      },
      {
        "src": "/schoolimages/1 (2).jpeg",
        "alt": "Montessori Prime campus — photo 4"
      },
      {
        "src": "/schoolimages/01 (2).jpg",
        "alt": "Montessori Prime campus — photo 5"
      },
      {
        "src": "/schoolimages/1 (2).jpg",
        "alt": "Montessori Prime campus — photo 6"
      },
      {
        "src": "/schoolimages/1 (3).jpeg",
        "alt": "Montessori Prime campus — photo 7"
      },
      {
        "src": "/schoolimages/01 (3).jpg",
        "alt": "Montessori Prime campus — photo 8"
      },
      {
        "src": "/schoolimages/1 (3).jpg",
        "alt": "Montessori Prime campus — photo 9"
      },
      {
        "src": "/schoolimages/1 (4).jpeg",
        "alt": "Montessori Prime campus — photo 10"
      },
      {
        "src": "/schoolimages/01 (4).jpg",
        "alt": "Montessori Prime campus — photo 11"
      },
      {
        "src": "/schoolimages/1 (4).jpg",
        "alt": "Montessori Prime campus — photo 12"
      },
      {
        "src": "/schoolimages/1 (5).jpeg",
        "alt": "Montessori Prime campus — photo 13"
      },
      {
        "src": "/schoolimages/01 (5).jpg",
        "alt": "Montessori Prime campus — photo 14"
      },
      {
        "src": "/schoolimages/1 (5).jpg",
        "alt": "Montessori Prime campus — photo 15"
      },
      {
        "src": "/schoolimages/1 (6).jpeg",
        "alt": "Montessori Prime campus — photo 16"
      },
      {
        "src": "/schoolimages/01 (6).jpg",
        "alt": "Montessori Prime campus — photo 17"
      },
      {
        "src": "/schoolimages/1 (6).jpg",
        "alt": "Montessori Prime campus — photo 18"
      },
      {
        "src": "/schoolimages/1 (7).jpeg",
        "alt": "Montessori Prime campus — photo 19"
      },
      {
        "src": "/schoolimages/01 (7).jpg",
        "alt": "Montessori Prime campus — photo 20"
      },
      {
        "src": "/schoolimages/1 (7).jpg",
        "alt": "Montessori Prime campus — photo 21"
      },
      {
        "src": "/schoolimages/1 (8).jpeg",
        "alt": "Montessori Prime campus — photo 22"
      },
      {
        "src": "/schoolimages/01 (8).jpg",
        "alt": "Montessori Prime campus — photo 23"
      },
      {
        "src": "/schoolimages/1 (8).jpg",
        "alt": "Montessori Prime campus — photo 24"
      },
      {
        "src": "/schoolimages/1 (9).jpeg",
        "alt": "Montessori Prime campus — photo 25"
      },
      {
        "src": "/schoolimages/01 (9).jpg",
        "alt": "Montessori Prime campus — photo 26"
      },
      {
        "src": "/schoolimages/1 (9).jpg",
        "alt": "Montessori Prime campus — photo 27"
      },
      {
        "src": "/schoolimages/1 (10).jpeg",
        "alt": "Montessori Prime campus — photo 28"
      },
      {
        "src": "/schoolimages/01 (10).jpg",
        "alt": "Montessori Prime campus — photo 29"
      },
      {
        "src": "/schoolimages/1 (10).jpg",
        "alt": "Montessori Prime campus — photo 30"
      },
      {
        "src": "/schoolimages/1 (11).jpeg",
        "alt": "Montessori Prime campus — photo 31"
      },
      {
        "src": "/schoolimages/01 (11).jpg",
        "alt": "Montessori Prime campus — photo 32"
      },
      {
        "src": "/schoolimages/1 (11).jpg",
        "alt": "Montessori Prime campus — photo 33"
      },
      {
        "src": "/schoolimages/1 (12).jpeg",
        "alt": "Montessori Prime campus — photo 34"
      },
      {
        "src": "/schoolimages/01 (12).jpg",
        "alt": "Montessori Prime campus — photo 35"
      },
      {
        "src": "/schoolimages/1 (12).jpg",
        "alt": "Montessori Prime campus — photo 36"
      },
      {
        "src": "/schoolimages/1 (13).jpeg",
        "alt": "Montessori Prime campus — photo 37"
      },
      {
        "src": "/schoolimages/01 (13).jpg",
        "alt": "Montessori Prime campus — photo 38"
      },
      {
        "src": "/schoolimages/1 (13).jpg",
        "alt": "Montessori Prime campus — photo 39"
      },
      {
        "src": "/schoolimages/1 (14).jpeg",
        "alt": "Montessori Prime campus — photo 40"
      },
      {
        "src": "/schoolimages/01 (14).jpg",
        "alt": "Montessori Prime campus — photo 41"
      },
      {
        "src": "/schoolimages/1 (14).jpg",
        "alt": "Montessori Prime campus — photo 42"
      },
      {
        "src": "/schoolimages/1 (15).jpeg",
        "alt": "Montessori Prime campus — photo 43"
      },
      {
        "src": "/schoolimages/01 (15).jpg",
        "alt": "Montessori Prime campus — photo 44"
      },
      {
        "src": "/schoolimages/1 (15).jpg",
        "alt": "Montessori Prime campus — photo 45"
      },
      {
        "src": "/schoolimages/1 (16).jpeg",
        "alt": "Montessori Prime campus — photo 46"
      },
      {
        "src": "/schoolimages/01 (16).jpg",
        "alt": "Montessori Prime campus — photo 47"
      },
      {
        "src": "/schoolimages/1 (16).jpg",
        "alt": "Montessori Prime campus — photo 48"
      },
      {
        "src": "/schoolimages/1 (17).jpeg",
        "alt": "Montessori Prime campus — photo 49"
      },
      {
        "src": "/schoolimages/01 (17).jpg",
        "alt": "Montessori Prime campus — photo 50"
      },
      {
        "src": "/schoolimages/1 (17).jpg",
        "alt": "Montessori Prime campus — photo 51"
      },
      {
        "src": "/schoolimages/1 (18).jpeg",
        "alt": "Montessori Prime campus — photo 52"
      },
      {
        "src": "/schoolimages/01 (18).jpg",
        "alt": "Montessori Prime campus — photo 53"
      },
      {
        "src": "/schoolimages/1 (18).jpg",
        "alt": "Montessori Prime campus — photo 54"
      },
      {
        "src": "/schoolimages/1 (19).jpeg",
        "alt": "Montessori Prime campus — photo 55"
      },
      {
        "src": "/schoolimages/01 (19).jpg",
        "alt": "Montessori Prime campus — photo 56"
      },
      {
        "src": "/schoolimages/1 (19).jpg",
        "alt": "Montessori Prime campus — photo 57"
      },
      {
        "src": "/schoolimages/1 (20).jpeg",
        "alt": "Montessori Prime campus — photo 58"
      },
      {
        "src": "/schoolimages/01 (20).jpg",
        "alt": "Montessori Prime campus — photo 59"
      },
      {
        "src": "/schoolimages/1 (20).jpg",
        "alt": "Montessori Prime campus — photo 60"
      },
      {
        "src": "/schoolimages/1 (21).jpeg",
        "alt": "Montessori Prime campus — photo 61"
      },
      {
        "src": "/schoolimages/01 (21).jpg",
        "alt": "Montessori Prime campus — photo 62"
      },
      {
        "src": "/schoolimages/1 (21).jpg",
        "alt": "Montessori Prime campus — photo 63"
      },
      {
        "src": "/schoolimages/1 (22).jpeg",
        "alt": "Montessori Prime campus — photo 64"
      },
      {
        "src": "/schoolimages/01 (22).jpg",
        "alt": "Montessori Prime campus — photo 65"
      },
      {
        "src": "/schoolimages/1 (22).jpg",
        "alt": "Montessori Prime campus — photo 66"
      },
      {
        "src": "/schoolimages/1 (23).jpeg",
        "alt": "Montessori Prime campus — photo 67"
      },
      {
        "src": "/schoolimages/01 (23).jpg",
        "alt": "Montessori Prime campus — photo 68"
      },
      {
        "src": "/schoolimages/1 (23).jpg",
        "alt": "Montessori Prime campus — photo 69"
      },
      {
        "src": "/schoolimages/1 (24).jpeg",
        "alt": "Montessori Prime campus — photo 70"
      },
      {
        "src": "/schoolimages/01 (24).jpg",
        "alt": "Montessori Prime campus — photo 71"
      },
      {
        "src": "/schoolimages/1 (24).jpg",
        "alt": "Montessori Prime campus — photo 72"
      },
      {
        "src": "/schoolimages/1 (25).jpeg",
        "alt": "Montessori Prime campus — photo 73"
      },
      {
        "src": "/schoolimages/01 (25).jpg",
        "alt": "Montessori Prime campus — photo 74"
      },
      {
        "src": "/schoolimages/1 (25).jpg",
        "alt": "Montessori Prime campus — photo 75"
      },
      {
        "src": "/schoolimages/1 (26).jpeg",
        "alt": "Montessori Prime campus — photo 76"
      },
      {
        "src": "/schoolimages/01 (26).jpg",
        "alt": "Montessori Prime campus — photo 77"
      },
      {
        "src": "/schoolimages/1 (26).jpg",
        "alt": "Montessori Prime campus — photo 78"
      },
      {
        "src": "/schoolimages/1 (27).jpeg",
        "alt": "Montessori Prime campus — photo 79"
      },
      {
        "src": "/schoolimages/01 (27).jpg",
        "alt": "Montessori Prime campus — photo 80"
      },
      {
        "src": "/schoolimages/1 (27).jpg",
        "alt": "Montessori Prime campus — photo 81"
      },
      {
        "src": "/schoolimages/1 (28).jpeg",
        "alt": "Montessori Prime campus — photo 82"
      },
      {
        "src": "/schoolimages/01 (28).jpg",
        "alt": "Montessori Prime campus — photo 83"
      },
      {
        "src": "/schoolimages/1 (28).jpg",
        "alt": "Montessori Prime campus — photo 84"
      },
      {
        "src": "/schoolimages/1 (29).jpeg",
        "alt": "Montessori Prime campus — photo 85"
      },
      {
        "src": "/schoolimages/01 (29).jpg",
        "alt": "Montessori Prime campus — photo 86"
      },
      {
        "src": "/schoolimages/1 (29).jpg",
        "alt": "Montessori Prime campus — photo 87"
      },
      {
        "src": "/schoolimages/1 (30).jpeg",
        "alt": "Montessori Prime campus — photo 88"
      },
      {
        "src": "/schoolimages/01 (30).jpg",
        "alt": "Montessori Prime campus — photo 89"
      },
      {
        "src": "/schoolimages/1 (30).jpg",
        "alt": "Montessori Prime campus — photo 90"
      },
      {
        "src": "/schoolimages/1 (31).jpeg",
        "alt": "Montessori Prime campus — photo 91"
      },
      {
        "src": "/schoolimages/01 (31).jpg",
        "alt": "Montessori Prime campus — photo 92"
      },
      {
        "src": "/schoolimages/1 (31).jpg",
        "alt": "Montessori Prime campus — photo 93"
      },
      {
        "src": "/schoolimages/1 (32).jpeg",
        "alt": "Montessori Prime campus — photo 94"
      },
      {
        "src": "/schoolimages/01 (32).jpg",
        "alt": "Montessori Prime campus — photo 95"
      },
      {
        "src": "/schoolimages/1 (32).jpg",
        "alt": "Montessori Prime campus — photo 96"
      },
      {
        "src": "/schoolimages/1 (33).jpeg",
        "alt": "Montessori Prime campus — photo 97"
      },
      {
        "src": "/schoolimages/01 (33).jpg",
        "alt": "Montessori Prime campus — photo 98"
      },
      {
        "src": "/schoolimages/1 (33).jpg",
        "alt": "Montessori Prime campus — photo 99"
      },
      {
        "src": "/schoolimages/1 (34).jpeg",
        "alt": "Montessori Prime campus — photo 100"
      },
      {
        "src": "/schoolimages/01 (34).jpg",
        "alt": "Montessori Prime campus — photo 101"
      },
      {
        "src": "/schoolimages/1 (34).jpg",
        "alt": "Montessori Prime campus — photo 102"
      },
      {
        "src": "/schoolimages/1 (35).jpeg",
        "alt": "Montessori Prime campus — photo 103"
      },
      {
        "src": "/schoolimages/01 (35).jpg",
        "alt": "Montessori Prime campus — photo 104"
      },
      {
        "src": "/schoolimages/1 (35).jpg",
        "alt": "Montessori Prime campus — photo 105"
      },
      {
        "src": "/schoolimages/1 (36).jpeg",
        "alt": "Montessori Prime campus — photo 106"
      },
      {
        "src": "/schoolimages/01 (36).jpg",
        "alt": "Montessori Prime campus — photo 107"
      },
      {
        "src": "/schoolimages/1 (36).jpg",
        "alt": "Montessori Prime campus — photo 108"
      },
      {
        "src": "/schoolimages/1 (37).jpeg",
        "alt": "Montessori Prime campus — photo 109"
      },
      {
        "src": "/schoolimages/01 (37).jpg",
        "alt": "Montessori Prime campus — photo 110"
      },
      {
        "src": "/schoolimages/1 (37).jpg",
        "alt": "Montessori Prime campus — photo 111"
      },
      {
        "src": "/schoolimages/01 (38).jpg",
        "alt": "Montessori Prime campus — photo 112"
      },
      {
        "src": "/schoolimages/1 (38).jpg",
        "alt": "Montessori Prime campus — photo 113"
      },
      {
        "src": "/schoolimages/01 (39).jpg",
        "alt": "Montessori Prime campus — photo 114"
      },
      {
        "src": "/schoolimages/1 (39).jpg",
        "alt": "Montessori Prime campus — photo 115"
      },
      {
        "src": "/schoolimages/01 (40).jpg",
        "alt": "Montessori Prime campus — photo 116"
      },
      {
        "src": "/schoolimages/1 (40).jpg",
        "alt": "Montessori Prime campus — photo 117"
      },
      {
        "src": "/schoolimages/01 (41).jpg",
        "alt": "Montessori Prime campus — photo 118"
      },
      {
        "src": "/schoolimages/1 (41).jpg",
        "alt": "Montessori Prime campus — photo 119"
      },
      {
        "src": "/schoolimages/01 (42).jpg",
        "alt": "Montessori Prime campus — photo 120"
      },
      {
        "src": "/schoolimages/1 (42).jpg",
        "alt": "Montessori Prime campus — photo 121"
      },
      {
        "src": "/schoolimages/01 (43).jpg",
        "alt": "Montessori Prime campus — photo 122"
      },
      {
        "src": "/schoolimages/1 (43).jpg",
        "alt": "Montessori Prime campus — photo 123"
      },
      {
        "src": "/schoolimages/01 (44).jpg",
        "alt": "Montessori Prime campus — photo 124"
      },
      {
        "src": "/schoolimages/1 (44).jpg",
        "alt": "Montessori Prime campus — photo 125"
      },
      {
        "src": "/schoolimages/01 (45).jpg",
        "alt": "Montessori Prime campus — photo 126"
      },
      {
        "src": "/schoolimages/1 (45).jpg",
        "alt": "Montessori Prime campus — photo 127"
      },
      {
        "src": "/schoolimages/01 (46).jpg",
        "alt": "Montessori Prime campus — photo 128"
      },
      {
        "src": "/schoolimages/1 (46).jpg",
        "alt": "Montessori Prime campus — photo 129"
      },
      {
        "src": "/schoolimages/01 (47).jpg",
        "alt": "Montessori Prime campus — photo 130"
      },
      {
        "src": "/schoolimages/1 (47).jpg",
        "alt": "Montessori Prime campus — photo 131"
      },
      {
        "src": "/schoolimages/01 (48).jpg",
        "alt": "Montessori Prime campus — photo 132"
      },
      {
        "src": "/schoolimages/1 (48).jpg",
        "alt": "Montessori Prime campus — photo 133"
      },
      {
        "src": "/schoolimages/01 (49).jpg",
        "alt": "Montessori Prime campus — photo 134"
      },
      {
        "src": "/schoolimages/1 (49).jpg",
        "alt": "Montessori Prime campus — photo 135"
      },
      {
        "src": "/schoolimages/01 (50).jpg",
        "alt": "Montessori Prime campus — photo 136"
      },
      {
        "src": "/schoolimages/1 (50).jpg",
        "alt": "Montessori Prime campus — photo 137"
      },
      {
        "src": "/schoolimages/01 (51).jpg",
        "alt": "Montessori Prime campus — photo 138"
      },
      {
        "src": "/schoolimages/1 (51).jpg",
        "alt": "Montessori Prime campus — photo 139"
      },
      {
        "src": "/schoolimages/01 (52).jpg",
        "alt": "Montessori Prime campus — photo 140"
      },
      {
        "src": "/schoolimages/1 (52).jpg",
        "alt": "Montessori Prime campus — photo 141"
      },
      {
        "src": "/schoolimages/01 (53).jpg",
        "alt": "Montessori Prime campus — photo 142"
      },
      {
        "src": "/schoolimages/1 (53).jpg",
        "alt": "Montessori Prime campus — photo 143"
      },
      {
        "src": "/schoolimages/01 (54).jpg",
        "alt": "Montessori Prime campus — photo 144"
      },
      {
        "src": "/schoolimages/1 (54).jpg",
        "alt": "Montessori Prime campus — photo 145"
      }
    ]
  }
];

export const schoolGalleries: LocalGallery[] = raw.map((g) => ({
  ...g,
  // encode each photo src for spaces / parens, and use the first photo as the cover.
  photos: g.photos.map((p) => ({ ...p, src: encodeURI(p.src) })),
  cover: encodeURI(g.photos[0].src),
}));

export function getSchoolGalleryBySlug(slug: string): LocalGallery | undefined {
  return schoolGalleries.find((g) => g.slug === slug);
}
