// One-off generator: scans public/schoolimages + public/groupedImages and emits
// data/schoolGallery.ts as static arrays. Run with: node scripts/genSchoolGallery.mjs
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const PUBLIC = join(ROOT, "public");

// Web-renderable raster formats only. HEIC is dropped (browsers can't display it).
const WEB_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"]);
const ext = (f) => f.slice(f.lastIndexOf(".")).toLowerCase();
const isImage = (f) => WEB_EXT.has(ext(f));

// Natural sort so "01 (2)" comes before "01 (10)".
const collator = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" });
const naturalSort = (a, b) => collator.compare(a, b);

// Folder name -> clean display name. Unmapped folders fall back to title-case.
const NAME_MAP = {
  "basket ball": "Basketball",
  "chair man sir": "Chairman Sir",
  "compuer lab": "Computer Lab",
  "study hr": "Study Hours",
  "tecnolagy": "Technology",
  "vollyball": "Volleyball",
  "mess": "Dining Hall",
  "mar.art": "Martial Arts",
  "testimony": "Testimonials",
  "lab": "Laboratory",
};
const titleCase = (s) =>
  s.replace(/[._]/g, " ").replace(/\s+/g, " ").trim()
    .split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
const displayName = (folder) => NAME_MAP[folder] ?? titleCase(folder);

const slugify = (name) =>
  name.toLowerCase().trim()
    .replace(/&/g, " and ")
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

const CREATED_ON = "27/05/2026 12:00:00 PM";

const galleries = [];

// 1) Grouped images: one gallery per non-empty subfolder.
const groupedRoot = join(PUBLIC, "groupedImages");
for (const folder of readdirSync(groupedRoot).sort(naturalSort)) {
  const dir = join(groupedRoot, folder);
  if (!statSync(dir).isDirectory()) continue;
  const files = readdirSync(dir).filter(isImage).sort(naturalSort);
  if (files.length === 0) continue;
  const name = displayName(folder);
  const photos = files.map((f, i) => ({
    src: `/groupedImages/${folder}/${f}`,
    alt: `${name} at Montessori Prime — photo ${i + 1}`,
  }));
  galleries.push({
    name,
    slug: slugify(name),
    count: photos.length,
    createdOn: CREATED_ON,
    photos,
  });
}

// 2) School images: a single flat gallery of standalone campus photos.
const schoolDir = join(PUBLIC, "schoolimages");
const schoolFiles = readdirSync(schoolDir).filter(isImage).sort(naturalSort);
if (schoolFiles.length) {
  const name = "Campus Life";
  const photos = schoolFiles.map((f, i) => ({
    src: `/schoolimages/${f}`,
    alt: `Montessori Prime campus — photo ${i + 1}`,
  }));
  galleries.push({
    name,
    slug: slugify(name),
    count: photos.length,
    createdOn: CREATED_ON,
    photos,
  });
}

// Emit TypeScript.
const header = `//File :- data/schoolGallery.ts
// AUTO-GENERATED by scripts/genSchoolGallery.mjs — do not edit photo lists by hand.
// Catalogs the local images under public/schoolimages and public/groupedImages.
// (HEIC files are intentionally excluded — browsers cannot render them.)

export type LocalPhoto = { src: string; alt: string };

export type LocalGallery = {
  name: string;
  slug: string;
  cover: string;
  count: number;
  createdOn: string;
  photos: LocalPhoto[];
};
`;

const body = `
const raw: Omit<LocalGallery, "cover">[] = ${JSON.stringify(galleries, null, 2)};

export const schoolGalleries: LocalGallery[] = raw.map((g) => ({
  ...g,
  // encode each photo src for spaces / parens, and use the first photo as the cover.
  photos: g.photos.map((p) => ({ ...p, src: encodeURI(p.src) })),
  cover: encodeURI(g.photos[0].src),
}));

export function getSchoolGalleryBySlug(slug: string): LocalGallery | undefined {
  return schoolGalleries.find((g) => g.slug === slug);
}
`;

writeFileSync(join(ROOT, "data", "schoolGallery.ts"), header + body);

// Console report.
const total = galleries.reduce((n, g) => n + g.count, 0);
console.log(`Wrote data/schoolGallery.ts`);
console.log(`Galleries: ${galleries.length}, total photos: ${total}`);
for (const g of galleries) console.log(`  - ${g.name} (${g.slug}) — ${g.count}`);
